功能: 测试用例-验证本地FM播放正常 # features/testcase-2016_08_2417_13_47_691990.feature:2

  场景: 测试用例-验证本地FM播放正常  # features/testcase-2016_08_2417_13_47_691990.feature:3
    当 < 打开收音机应用        # steps/step_launcher.py:14
    当 < 打开FM_AM选择界面    # steps/step_radio.py:10
    当 < 播放指定FM节目       # steps/step_radio.py:15
      | fm_no |
      | 97.5  |
    那么 < 验证播放的FM编号一致   # steps/step_radio.py:21
      | chk_fm_no |
      | 97.5      |

功能: 测试用例-搜索并播放网络电台 # features/testcase-2016_08_2417_13_47_730677.feature:2

  场景: 测试用例-搜索并播放网络电台  # features/testcase-2016_08_2417_13_47_730677.feature:3
    当 < 打开收音机应用       # steps/step_launcher.py:14
    当 < 打开搜索界面        # steps/step_radio.py:108
    当 < 输入电台搜索关键字     # steps/step_radio.py:112
      | key_word |
      | 南京       |
    当 < 随机播放搜索电台      # steps/step_radio.py:137
      | o_result |
      | o_fm     |
      Traceback (most recent call last):
        File "/usr/local/lib/python3.4/site-packages/behave/model.py", line 1456, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.4/site-packages/behave/model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "steps/step_radio.py", line 141, in step_impl
          fm_no = Radio().click_radio_search_list_title_random_ele()
        File "/home/ogq/pateo/AT/ATP/autotestproject/actions/radio.py", line 602, in click_radio_search_list_title_random_ele
          Utils().raise_Exception_info('收音机搜索结果为空')
        File "/home/ogq/pateo/AT/ATP/autotestproject/utils/utils.py", line 106, in raise_Exception_info
          raise Exception('用例运行失败，' + err_msg + '请参考截图信息: file:///' + png_path)
      Exception: 用例运行失败，收音机搜索结果为空请参考截图信息: file:////home/ogq/pateo/AT/autotestLog/20160824/screenshots/20160824171449.png
      
      Captured stdout:
      /home/ogq/pateo/AT/autotestLog/20160824/screenshots/20160824171449.png
      开始检查应用是否crash

    那么 < 验证播放FM节目一致   # None
      | chk_name |
      | o_result |

